version: 2

jobs:
  test:
    docker:
      - image: circleci/openjdk:8u171-jdk-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run: make ci_build
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: make ci_test

workflows:
  version: 2
  test:
    jobs:
      - test

