#
# Encapsulate the common tasks in a Makefile so one does not need to be familiar
# with gradle (or any Java-specific build tool) to get useful things done.
#
.PHONY: build clean

build:
	gradle build

clean:
	gradle clean

publish:
	gradle bintray
