/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lightstep.tracer.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-7-13")
public class MetricsSample implements org.apache.thrift.TBase<MetricsSample, MetricsSample._Fields>, java.io.Serializable, Cloneable, Comparable<MetricsSample> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MetricsSample");

  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField INT64_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("int64_value", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField DOUBLE_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("double_value", org.apache.thrift.protocol.TType.DOUBLE, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MetricsSampleStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MetricsSampleTupleSchemeFactory());
  }

  public String name; // required
  public long int64_value; // optional
  public double double_value; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NAME((short)1, "name"),
    INT64_VALUE((short)2, "int64_value"),
    DOUBLE_VALUE((short)3, "double_value");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NAME
          return NAME;
        case 2: // INT64_VALUE
          return INT64_VALUE;
        case 3: // DOUBLE_VALUE
          return DOUBLE_VALUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __INT64_VALUE_ISSET_ID = 0;
  private static final int __DOUBLE_VALUE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.INT64_VALUE,_Fields.DOUBLE_VALUE};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.INT64_VALUE, new org.apache.thrift.meta_data.FieldMetaData("int64_value", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.DOUBLE_VALUE, new org.apache.thrift.meta_data.FieldMetaData("double_value", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MetricsSample.class, metaDataMap);
  }

  public MetricsSample() {
  }

  public MetricsSample(
    String name)
  {
    this();
    this.name = name;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MetricsSample(MetricsSample other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetName()) {
      this.name = other.name;
    }
    this.int64_value = other.int64_value;
    this.double_value = other.double_value;
  }

  public MetricsSample deepCopy() {
    return new MetricsSample(this);
  }

  @Override
  public void clear() {
    this.name = null;
    setInt64_valueIsSet(false);
    this.int64_value = 0;
    setDouble_valueIsSet(false);
    this.double_value = 0.0;
  }

  public String getName() {
    return this.name;
  }

  public MetricsSample setName(String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public long getInt64_value() {
    return this.int64_value;
  }

  public MetricsSample setInt64_value(long int64_value) {
    this.int64_value = int64_value;
    setInt64_valueIsSet(true);
    return this;
  }

  public void unsetInt64_value() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __INT64_VALUE_ISSET_ID);
  }

  /** Returns true if field int64_value is set (has been assigned a value) and false otherwise */
  public boolean isSetInt64_value() {
    return EncodingUtils.testBit(__isset_bitfield, __INT64_VALUE_ISSET_ID);
  }

  public void setInt64_valueIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __INT64_VALUE_ISSET_ID, value);
  }

  public double getDouble_value() {
    return this.double_value;
  }

  public MetricsSample setDouble_value(double double_value) {
    this.double_value = double_value;
    setDouble_valueIsSet(true);
    return this;
  }

  public void unsetDouble_value() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DOUBLE_VALUE_ISSET_ID);
  }

  /** Returns true if field double_value is set (has been assigned a value) and false otherwise */
  public boolean isSetDouble_value() {
    return EncodingUtils.testBit(__isset_bitfield, __DOUBLE_VALUE_ISSET_ID);
  }

  public void setDouble_valueIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DOUBLE_VALUE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((String)value);
      }
      break;

    case INT64_VALUE:
      if (value == null) {
        unsetInt64_value();
      } else {
        setInt64_value((Long)value);
      }
      break;

    case DOUBLE_VALUE:
      if (value == null) {
        unsetDouble_value();
      } else {
        setDouble_value((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NAME:
      return getName();

    case INT64_VALUE:
      return Long.valueOf(getInt64_value());

    case DOUBLE_VALUE:
      return Double.valueOf(getDouble_value());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NAME:
      return isSetName();
    case INT64_VALUE:
      return isSetInt64_value();
    case DOUBLE_VALUE:
      return isSetDouble_value();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MetricsSample)
      return this.equals((MetricsSample)that);
    return false;
  }

  public boolean equals(MetricsSample that) {
    if (that == null)
      return false;

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_int64_value = true && this.isSetInt64_value();
    boolean that_present_int64_value = true && that.isSetInt64_value();
    if (this_present_int64_value || that_present_int64_value) {
      if (!(this_present_int64_value && that_present_int64_value))
        return false;
      if (this.int64_value != that.int64_value)
        return false;
    }

    boolean this_present_double_value = true && this.isSetDouble_value();
    boolean that_present_double_value = true && that.isSetDouble_value();
    if (this_present_double_value || that_present_double_value) {
      if (!(this_present_double_value && that_present_double_value))
        return false;
      if (this.double_value != that.double_value)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_name = true && (isSetName());
    list.add(present_name);
    if (present_name)
      list.add(name);

    boolean present_int64_value = true && (isSetInt64_value());
    list.add(present_int64_value);
    if (present_int64_value)
      list.add(int64_value);

    boolean present_double_value = true && (isSetDouble_value());
    list.add(present_double_value);
    if (present_double_value)
      list.add(double_value);

    return list.hashCode();
  }

  @Override
  public int compareTo(MetricsSample other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetInt64_value()).compareTo(other.isSetInt64_value());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInt64_value()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.int64_value, other.int64_value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDouble_value()).compareTo(other.isSetDouble_value());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDouble_value()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.double_value, other.double_value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MetricsSample(");
    boolean first = true;

    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (isSetInt64_value()) {
      if (!first) sb.append(", ");
      sb.append("int64_value:");
      sb.append(this.int64_value);
      first = false;
    }
    if (isSetDouble_value()) {
      if (!first) sb.append(", ");
      sb.append("double_value:");
      sb.append(this.double_value);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (name == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'name' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MetricsSampleStandardSchemeFactory implements SchemeFactory {
    public MetricsSampleStandardScheme getScheme() {
      return new MetricsSampleStandardScheme();
    }
  }

  private static class MetricsSampleStandardScheme extends StandardScheme<MetricsSample> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MetricsSample struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // INT64_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.int64_value = iprot.readI64();
              struct.setInt64_valueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DOUBLE_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.double_value = iprot.readDouble();
              struct.setDouble_valueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MetricsSample struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      if (struct.isSetInt64_value()) {
        oprot.writeFieldBegin(INT64_VALUE_FIELD_DESC);
        oprot.writeI64(struct.int64_value);
        oprot.writeFieldEnd();
      }
      if (struct.isSetDouble_value()) {
        oprot.writeFieldBegin(DOUBLE_VALUE_FIELD_DESC);
        oprot.writeDouble(struct.double_value);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MetricsSampleTupleSchemeFactory implements SchemeFactory {
    public MetricsSampleTupleScheme getScheme() {
      return new MetricsSampleTupleScheme();
    }
  }

  private static class MetricsSampleTupleScheme extends TupleScheme<MetricsSample> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MetricsSample struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.name);
      BitSet optionals = new BitSet();
      if (struct.isSetInt64_value()) {
        optionals.set(0);
      }
      if (struct.isSetDouble_value()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetInt64_value()) {
        oprot.writeI64(struct.int64_value);
      }
      if (struct.isSetDouble_value()) {
        oprot.writeDouble(struct.double_value);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MetricsSample struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.name = iprot.readString();
      struct.setNameIsSet(true);
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.int64_value = iprot.readI64();
        struct.setInt64_valueIsSet(true);
      }
      if (incoming.get(1)) {
        struct.double_value = iprot.readDouble();
        struct.setDouble_valueIsSet(true);
      }
    }
  }

}

