// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

package com.lightstep.tracer.grpc;

public interface AuthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightstep.collector.Auth)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string access_token = 1;</code>
   */
  java.lang.String getAccessToken();
  /**
   * <code>optional string access_token = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();
}
