// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

package com.lightstep.tracer.grpc;

public final class Collector {
  private Collector() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_SpanContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_SpanContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_SpanContext_BaggageEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_SpanContext_BaggageEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_KeyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_KeyValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_Log_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_Log_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_Reference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_Reference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_Span_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_Span_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_Reporter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_Reporter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_MetricsSample_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_MetricsSample_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_InternalMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_InternalMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_Auth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_Auth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_ReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_ReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_Command_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_Command_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_ReportResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_ReportResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017collector.proto\022\023lightstep.collector\032\037" +
      "google/protobuf/timestamp.proto\"\240\001\n\013Span" +
      "Context\022\020\n\010trace_id\030\001 \001(\004\022\017\n\007span_id\030\002 \001" +
      "(\004\022>\n\007baggage\030\003 \003(\0132-.lightstep.collecto" +
      "r.SpanContext.BaggageEntry\032.\n\014BaggageEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\221\001\n\010K" +
      "eyValue\022\013\n\003key\030\001 \001(\t\022\026\n\014string_value\030\002 \001" +
      "(\tH\000\022\023\n\tint_value\030\003 \001(\003H\000\022\026\n\014double_valu" +
      "e\030\004 \001(\001H\000\022\024\n\nbool_value\030\005 \001(\010H\000\022\024\n\njson_" +
      "value\030\006 \001(\tH\000B\007\n\005value\"f\n\003Log\022-\n\ttimesta",
      "mp\030\001 \001(\0132\032.google.protobuf.Timestamp\0220\n\t" +
      "keyvalues\030\002 \003(\0132\035.lightstep.collector.Ke" +
      "yValue\"\266\001\n\tReference\022A\n\014relationship\030\001 \001" +
      "(\0162+.lightstep.collector.Reference.Relat" +
      "ionship\0226\n\014span_context\030\002 \001(\0132 .lightste" +
      "p.collector.SpanContext\".\n\014Relationship\022" +
      "\014\n\010CHILD_OF\020\000\022\020\n\014FOLLOWS_FROM\020\001\"\255\002\n\004Span" +
      "\0226\n\014span_context\030\001 \001(\0132 .lightstep.colle" +
      "ctor.SpanContext\022\026\n\016operation_name\030\002 \001(\t" +
      "\0222\n\nreferences\030\003 \003(\0132\036.lightstep.collect",
      "or.Reference\0223\n\017start_timestamp\030\004 \001(\0132\032." +
      "google.protobuf.Timestamp\022\027\n\017duration_mi" +
      "cros\030\005 \001(\004\022+\n\004tags\030\006 \003(\0132\035.lightstep.col" +
      "lector.KeyValue\022&\n\004logs\030\007 \003(\0132\030.lightste" +
      "p.collector.Log\"L\n\010Reporter\022\023\n\013reporter_" +
      "id\030\001 \001(\004\022+\n\004tags\030\004 \003(\0132\035.lightstep.colle" +
      "ctor.KeyValue\"S\n\rMetricsSample\022\014\n\004name\030\001" +
      " \001(\t\022\023\n\tint_value\030\002 \001(\003H\000\022\026\n\014double_valu" +
      "e\030\003 \001(\001H\000B\007\n\005value\"\357\001\n\017InternalMetrics\0223" +
      "\n\017start_timestamp\030\001 \001(\0132\032.google.protobu",
      "f.Timestamp\022\027\n\017duration_micros\030\002 \001(\004\022&\n\004" +
      "logs\030\003 \003(\0132\030.lightstep.collector.Log\0222\n\006" +
      "counts\030\004 \003(\0132\".lightstep.collector.Metri" +
      "csSample\0222\n\006gauges\030\005 \003(\0132\".lightstep.col" +
      "lector.MetricsSample\"\034\n\004Auth\022\024\n\014access_t" +
      "oken\030\001 \001(\t\"\364\001\n\rReportRequest\022/\n\010reporter" +
      "\030\001 \001(\0132\035.lightstep.collector.Reporter\022\'\n" +
      "\004auth\030\002 \001(\0132\031.lightstep.collector.Auth\022(" +
      "\n\005spans\030\003 \003(\0132\031.lightstep.collector.Span" +
      "\022\037\n\027timestamp_offset_micros\030\005 \001(\r\022>\n\020int",
      "ernal_metrics\030\006 \001(\0132$.lightstep.collecto" +
      "r.InternalMetrics\"\032\n\007Command\022\017\n\007disable\030" +
      "\001 \001(\010\"\277\001\n\016ReportResponse\022.\n\010commands\030\001 \003" +
      "(\0132\034.lightstep.collector.Command\0225\n\021rece" +
      "ive_timestamp\030\002 \001(\0132\032.google.protobuf.Ti" +
      "mestamp\0226\n\022transmit_timestamp\030\003 \001(\0132\032.go" +
      "ogle.protobuf.Timestamp\022\016\n\006errors\030\004 \003(\t2" +
      "e\n\020CollectorService\022Q\n\006Report\022\".lightste" +
      "p.collector.ReportRequest\032#.lightstep.co" +
      "llector.ReportResponseB1\n\031com.lightstep.",
      "tracer.grpcP\001Z\013collectorpb\242\002\004LSPBb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_lightstep_collector_SpanContext_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightstep_collector_SpanContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_SpanContext_descriptor,
        new java.lang.String[] { "TraceId", "SpanId", "Baggage", });
    internal_static_lightstep_collector_SpanContext_BaggageEntry_descriptor =
      internal_static_lightstep_collector_SpanContext_descriptor.getNestedTypes().get(0);
    internal_static_lightstep_collector_SpanContext_BaggageEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_SpanContext_BaggageEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lightstep_collector_KeyValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lightstep_collector_KeyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_KeyValue_descriptor,
        new java.lang.String[] { "Key", "StringValue", "IntValue", "DoubleValue", "BoolValue", "JsonValue", "Value", });
    internal_static_lightstep_collector_Log_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lightstep_collector_Log_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_Log_descriptor,
        new java.lang.String[] { "Timestamp", "Keyvalues", });
    internal_static_lightstep_collector_Reference_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lightstep_collector_Reference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_Reference_descriptor,
        new java.lang.String[] { "Relationship", "SpanContext", });
    internal_static_lightstep_collector_Span_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_lightstep_collector_Span_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_Span_descriptor,
        new java.lang.String[] { "SpanContext", "OperationName", "References", "StartTimestamp", "DurationMicros", "Tags", "Logs", });
    internal_static_lightstep_collector_Reporter_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_lightstep_collector_Reporter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_Reporter_descriptor,
        new java.lang.String[] { "ReporterId", "Tags", });
    internal_static_lightstep_collector_MetricsSample_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_lightstep_collector_MetricsSample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_MetricsSample_descriptor,
        new java.lang.String[] { "Name", "IntValue", "DoubleValue", "Value", });
    internal_static_lightstep_collector_InternalMetrics_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_lightstep_collector_InternalMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_InternalMetrics_descriptor,
        new java.lang.String[] { "StartTimestamp", "DurationMicros", "Logs", "Counts", "Gauges", });
    internal_static_lightstep_collector_Auth_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_lightstep_collector_Auth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_Auth_descriptor,
        new java.lang.String[] { "AccessToken", });
    internal_static_lightstep_collector_ReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_lightstep_collector_ReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_ReportRequest_descriptor,
        new java.lang.String[] { "Reporter", "Auth", "Spans", "TimestampOffsetMicros", "InternalMetrics", });
    internal_static_lightstep_collector_Command_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_lightstep_collector_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_Command_descriptor,
        new java.lang.String[] { "Disable", });
    internal_static_lightstep_collector_ReportResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_lightstep_collector_ReportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_ReportResponse_descriptor,
        new java.lang.String[] { "Commands", "ReceiveTimestamp", "TransmitTimestamp", "Errors", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
