// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

package com.lightstep.tracer.grpc;

/**
 * Protobuf type {@code lightstep.collector.Log}
 */
public  final class Log extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lightstep.collector.Log)
    LogOrBuilder {
  // Use Log.newBuilder() to construct.
  private Log(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Log() {
    keyvalues_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Log(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              keyvalues_ = new java.util.ArrayList<com.lightstep.tracer.grpc.KeyValue>();
              mutable_bitField0_ |= 0x00000002;
            }
            keyvalues_.add(
                input.readMessage(com.lightstep.tracer.grpc.KeyValue.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        keyvalues_ = java.util.Collections.unmodifiableList(keyvalues_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_Log_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_Log_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lightstep.tracer.grpc.Log.class, com.lightstep.tracer.grpc.Log.Builder.class);
  }

  private int bitField0_;
  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
   */
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
   */
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  public static final int KEYVALUES_FIELD_NUMBER = 2;
  private java.util.List<com.lightstep.tracer.grpc.KeyValue> keyvalues_;
  /**
   * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
   */
  public java.util.List<com.lightstep.tracer.grpc.KeyValue> getKeyvaluesList() {
    return keyvalues_;
  }
  /**
   * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
   */
  public java.util.List<? extends com.lightstep.tracer.grpc.KeyValueOrBuilder> 
      getKeyvaluesOrBuilderList() {
    return keyvalues_;
  }
  /**
   * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
   */
  public int getKeyvaluesCount() {
    return keyvalues_.size();
  }
  /**
   * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
   */
  public com.lightstep.tracer.grpc.KeyValue getKeyvalues(int index) {
    return keyvalues_.get(index);
  }
  /**
   * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
   */
  public com.lightstep.tracer.grpc.KeyValueOrBuilder getKeyvaluesOrBuilder(
      int index) {
    return keyvalues_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestamp_ != null) {
      output.writeMessage(1, getTimestamp());
    }
    for (int i = 0; i < keyvalues_.size(); i++) {
      output.writeMessage(2, keyvalues_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTimestamp());
    }
    for (int i = 0; i < keyvalues_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, keyvalues_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lightstep.tracer.grpc.Log)) {
      return super.equals(obj);
    }
    com.lightstep.tracer.grpc.Log other = (com.lightstep.tracer.grpc.Log) obj;

    boolean result = true;
    result = result && (hasTimestamp() == other.hasTimestamp());
    if (hasTimestamp()) {
      result = result && getTimestamp()
          .equals(other.getTimestamp());
    }
    result = result && getKeyvaluesList()
        .equals(other.getKeyvaluesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (getKeyvaluesCount() > 0) {
      hash = (37 * hash) + KEYVALUES_FIELD_NUMBER;
      hash = (53 * hash) + getKeyvaluesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lightstep.tracer.grpc.Log parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lightstep.tracer.grpc.Log parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lightstep.tracer.grpc.Log parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lightstep.tracer.grpc.Log parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lightstep.tracer.grpc.Log parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lightstep.tracer.grpc.Log parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lightstep.tracer.grpc.Log parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lightstep.tracer.grpc.Log parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lightstep.tracer.grpc.Log parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lightstep.tracer.grpc.Log parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lightstep.tracer.grpc.Log prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lightstep.collector.Log}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lightstep.collector.Log)
      com.lightstep.tracer.grpc.LogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_Log_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_Log_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lightstep.tracer.grpc.Log.class, com.lightstep.tracer.grpc.Log.Builder.class);
    }

    // Construct using com.lightstep.tracer.grpc.Log.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getKeyvaluesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      if (keyvaluesBuilder_ == null) {
        keyvalues_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        keyvaluesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_Log_descriptor;
    }

    public com.lightstep.tracer.grpc.Log getDefaultInstanceForType() {
      return com.lightstep.tracer.grpc.Log.getDefaultInstance();
    }

    public com.lightstep.tracer.grpc.Log build() {
      com.lightstep.tracer.grpc.Log result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lightstep.tracer.grpc.Log buildPartial() {
      com.lightstep.tracer.grpc.Log result = new com.lightstep.tracer.grpc.Log(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      if (keyvaluesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          keyvalues_ = java.util.Collections.unmodifiableList(keyvalues_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.keyvalues_ = keyvalues_;
      } else {
        result.keyvalues_ = keyvaluesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lightstep.tracer.grpc.Log) {
        return mergeFrom((com.lightstep.tracer.grpc.Log)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lightstep.tracer.grpc.Log other) {
      if (other == com.lightstep.tracer.grpc.Log.getDefaultInstance()) return this;
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (keyvaluesBuilder_ == null) {
        if (!other.keyvalues_.isEmpty()) {
          if (keyvalues_.isEmpty()) {
            keyvalues_ = other.keyvalues_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureKeyvaluesIsMutable();
            keyvalues_.addAll(other.keyvalues_);
          }
          onChanged();
        }
      } else {
        if (!other.keyvalues_.isEmpty()) {
          if (keyvaluesBuilder_.isEmpty()) {
            keyvaluesBuilder_.dispose();
            keyvaluesBuilder_ = null;
            keyvalues_ = other.keyvalues_;
            bitField0_ = (bitField0_ & ~0x00000002);
            keyvaluesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getKeyvaluesFieldBuilder() : null;
          } else {
            keyvaluesBuilder_.addAllMessages(other.keyvalues_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lightstep.tracer.grpc.Log parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lightstep.tracer.grpc.Log) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Timestamp timestamp_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private java.util.List<com.lightstep.tracer.grpc.KeyValue> keyvalues_ =
      java.util.Collections.emptyList();
    private void ensureKeyvaluesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        keyvalues_ = new java.util.ArrayList<com.lightstep.tracer.grpc.KeyValue>(keyvalues_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.lightstep.tracer.grpc.KeyValue, com.lightstep.tracer.grpc.KeyValue.Builder, com.lightstep.tracer.grpc.KeyValueOrBuilder> keyvaluesBuilder_;

    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public java.util.List<com.lightstep.tracer.grpc.KeyValue> getKeyvaluesList() {
      if (keyvaluesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(keyvalues_);
      } else {
        return keyvaluesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public int getKeyvaluesCount() {
      if (keyvaluesBuilder_ == null) {
        return keyvalues_.size();
      } else {
        return keyvaluesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public com.lightstep.tracer.grpc.KeyValue getKeyvalues(int index) {
      if (keyvaluesBuilder_ == null) {
        return keyvalues_.get(index);
      } else {
        return keyvaluesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public Builder setKeyvalues(
        int index, com.lightstep.tracer.grpc.KeyValue value) {
      if (keyvaluesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyvaluesIsMutable();
        keyvalues_.set(index, value);
        onChanged();
      } else {
        keyvaluesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public Builder setKeyvalues(
        int index, com.lightstep.tracer.grpc.KeyValue.Builder builderForValue) {
      if (keyvaluesBuilder_ == null) {
        ensureKeyvaluesIsMutable();
        keyvalues_.set(index, builderForValue.build());
        onChanged();
      } else {
        keyvaluesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public Builder addKeyvalues(com.lightstep.tracer.grpc.KeyValue value) {
      if (keyvaluesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyvaluesIsMutable();
        keyvalues_.add(value);
        onChanged();
      } else {
        keyvaluesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public Builder addKeyvalues(
        int index, com.lightstep.tracer.grpc.KeyValue value) {
      if (keyvaluesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyvaluesIsMutable();
        keyvalues_.add(index, value);
        onChanged();
      } else {
        keyvaluesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public Builder addKeyvalues(
        com.lightstep.tracer.grpc.KeyValue.Builder builderForValue) {
      if (keyvaluesBuilder_ == null) {
        ensureKeyvaluesIsMutable();
        keyvalues_.add(builderForValue.build());
        onChanged();
      } else {
        keyvaluesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public Builder addKeyvalues(
        int index, com.lightstep.tracer.grpc.KeyValue.Builder builderForValue) {
      if (keyvaluesBuilder_ == null) {
        ensureKeyvaluesIsMutable();
        keyvalues_.add(index, builderForValue.build());
        onChanged();
      } else {
        keyvaluesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public Builder addAllKeyvalues(
        java.lang.Iterable<? extends com.lightstep.tracer.grpc.KeyValue> values) {
      if (keyvaluesBuilder_ == null) {
        ensureKeyvaluesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keyvalues_);
        onChanged();
      } else {
        keyvaluesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public Builder clearKeyvalues() {
      if (keyvaluesBuilder_ == null) {
        keyvalues_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        keyvaluesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public Builder removeKeyvalues(int index) {
      if (keyvaluesBuilder_ == null) {
        ensureKeyvaluesIsMutable();
        keyvalues_.remove(index);
        onChanged();
      } else {
        keyvaluesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public com.lightstep.tracer.grpc.KeyValue.Builder getKeyvaluesBuilder(
        int index) {
      return getKeyvaluesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public com.lightstep.tracer.grpc.KeyValueOrBuilder getKeyvaluesOrBuilder(
        int index) {
      if (keyvaluesBuilder_ == null) {
        return keyvalues_.get(index);  } else {
        return keyvaluesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public java.util.List<? extends com.lightstep.tracer.grpc.KeyValueOrBuilder> 
         getKeyvaluesOrBuilderList() {
      if (keyvaluesBuilder_ != null) {
        return keyvaluesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(keyvalues_);
      }
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public com.lightstep.tracer.grpc.KeyValue.Builder addKeyvaluesBuilder() {
      return getKeyvaluesFieldBuilder().addBuilder(
          com.lightstep.tracer.grpc.KeyValue.getDefaultInstance());
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public com.lightstep.tracer.grpc.KeyValue.Builder addKeyvaluesBuilder(
        int index) {
      return getKeyvaluesFieldBuilder().addBuilder(
          index, com.lightstep.tracer.grpc.KeyValue.getDefaultInstance());
    }
    /**
     * <code>repeated .lightstep.collector.KeyValue keyvalues = 2;</code>
     */
    public java.util.List<com.lightstep.tracer.grpc.KeyValue.Builder> 
         getKeyvaluesBuilderList() {
      return getKeyvaluesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.lightstep.tracer.grpc.KeyValue, com.lightstep.tracer.grpc.KeyValue.Builder, com.lightstep.tracer.grpc.KeyValueOrBuilder> 
        getKeyvaluesFieldBuilder() {
      if (keyvaluesBuilder_ == null) {
        keyvaluesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.lightstep.tracer.grpc.KeyValue, com.lightstep.tracer.grpc.KeyValue.Builder, com.lightstep.tracer.grpc.KeyValueOrBuilder>(
                keyvalues_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        keyvalues_ = null;
      }
      return keyvaluesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:lightstep.collector.Log)
  }

  // @@protoc_insertion_point(class_scope:lightstep.collector.Log)
  private static final com.lightstep.tracer.grpc.Log DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lightstep.tracer.grpc.Log();
  }

  public static com.lightstep.tracer.grpc.Log getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Log>
      PARSER = new com.google.protobuf.AbstractParser<Log>() {
    public Log parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Log(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Log> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Log> getParserForType() {
    return PARSER;
  }

  public com.lightstep.tracer.grpc.Log getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

