// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

package com.lightstep.tracer.grpc;

/**
 * Protobuf type {@code lightstep.collector.Reference}
 */
public  final class Reference extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lightstep.collector.Reference)
    ReferenceOrBuilder {
  // Use Reference.newBuilder() to construct.
  private Reference(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Reference() {
    relationship_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Reference(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            relationship_ = rawValue;
            break;
          }
          case 18: {
            com.lightstep.tracer.grpc.SpanContext.Builder subBuilder = null;
            if (spanContext_ != null) {
              subBuilder = spanContext_.toBuilder();
            }
            spanContext_ = input.readMessage(com.lightstep.tracer.grpc.SpanContext.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(spanContext_);
              spanContext_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_Reference_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_Reference_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lightstep.tracer.grpc.Reference.class, com.lightstep.tracer.grpc.Reference.Builder.class);
  }

  /**
   * Protobuf enum {@code lightstep.collector.Reference.Relationship}
   */
  public enum Relationship
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CHILD_OF = 0;</code>
     */
    CHILD_OF(0),
    /**
     * <code>FOLLOWS_FROM = 1;</code>
     */
    FOLLOWS_FROM(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CHILD_OF = 0;</code>
     */
    public static final int CHILD_OF_VALUE = 0;
    /**
     * <code>FOLLOWS_FROM = 1;</code>
     */
    public static final int FOLLOWS_FROM_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Relationship valueOf(int value) {
      return forNumber(value);
    }

    public static Relationship forNumber(int value) {
      switch (value) {
        case 0: return CHILD_OF;
        case 1: return FOLLOWS_FROM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Relationship>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Relationship> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Relationship>() {
            public Relationship findValueByNumber(int number) {
              return Relationship.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lightstep.tracer.grpc.Reference.getDescriptor().getEnumTypes().get(0);
    }

    private static final Relationship[] VALUES = values();

    public static Relationship valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Relationship(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:lightstep.collector.Reference.Relationship)
  }

  public static final int RELATIONSHIP_FIELD_NUMBER = 1;
  private int relationship_;
  /**
   * <code>optional .lightstep.collector.Reference.Relationship relationship = 1;</code>
   */
  public int getRelationshipValue() {
    return relationship_;
  }
  /**
   * <code>optional .lightstep.collector.Reference.Relationship relationship = 1;</code>
   */
  public com.lightstep.tracer.grpc.Reference.Relationship getRelationship() {
    com.lightstep.tracer.grpc.Reference.Relationship result = com.lightstep.tracer.grpc.Reference.Relationship.valueOf(relationship_);
    return result == null ? com.lightstep.tracer.grpc.Reference.Relationship.UNRECOGNIZED : result;
  }

  public static final int SPAN_CONTEXT_FIELD_NUMBER = 2;
  private com.lightstep.tracer.grpc.SpanContext spanContext_;
  /**
   * <code>optional .lightstep.collector.SpanContext span_context = 2;</code>
   */
  public boolean hasSpanContext() {
    return spanContext_ != null;
  }
  /**
   * <code>optional .lightstep.collector.SpanContext span_context = 2;</code>
   */
  public com.lightstep.tracer.grpc.SpanContext getSpanContext() {
    return spanContext_ == null ? com.lightstep.tracer.grpc.SpanContext.getDefaultInstance() : spanContext_;
  }
  /**
   * <code>optional .lightstep.collector.SpanContext span_context = 2;</code>
   */
  public com.lightstep.tracer.grpc.SpanContextOrBuilder getSpanContextOrBuilder() {
    return getSpanContext();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (relationship_ != com.lightstep.tracer.grpc.Reference.Relationship.CHILD_OF.getNumber()) {
      output.writeEnum(1, relationship_);
    }
    if (spanContext_ != null) {
      output.writeMessage(2, getSpanContext());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (relationship_ != com.lightstep.tracer.grpc.Reference.Relationship.CHILD_OF.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, relationship_);
    }
    if (spanContext_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSpanContext());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lightstep.tracer.grpc.Reference)) {
      return super.equals(obj);
    }
    com.lightstep.tracer.grpc.Reference other = (com.lightstep.tracer.grpc.Reference) obj;

    boolean result = true;
    result = result && relationship_ == other.relationship_;
    result = result && (hasSpanContext() == other.hasSpanContext());
    if (hasSpanContext()) {
      result = result && getSpanContext()
          .equals(other.getSpanContext());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + RELATIONSHIP_FIELD_NUMBER;
    hash = (53 * hash) + relationship_;
    if (hasSpanContext()) {
      hash = (37 * hash) + SPAN_CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getSpanContext().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lightstep.tracer.grpc.Reference parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lightstep.tracer.grpc.Reference parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lightstep.tracer.grpc.Reference parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lightstep.tracer.grpc.Reference parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lightstep.tracer.grpc.Reference parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lightstep.tracer.grpc.Reference parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lightstep.tracer.grpc.Reference parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lightstep.tracer.grpc.Reference parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lightstep.tracer.grpc.Reference parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lightstep.tracer.grpc.Reference parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lightstep.tracer.grpc.Reference prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lightstep.collector.Reference}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lightstep.collector.Reference)
      com.lightstep.tracer.grpc.ReferenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_Reference_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_Reference_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lightstep.tracer.grpc.Reference.class, com.lightstep.tracer.grpc.Reference.Builder.class);
    }

    // Construct using com.lightstep.tracer.grpc.Reference.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      relationship_ = 0;

      if (spanContextBuilder_ == null) {
        spanContext_ = null;
      } else {
        spanContext_ = null;
        spanContextBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_Reference_descriptor;
    }

    public com.lightstep.tracer.grpc.Reference getDefaultInstanceForType() {
      return com.lightstep.tracer.grpc.Reference.getDefaultInstance();
    }

    public com.lightstep.tracer.grpc.Reference build() {
      com.lightstep.tracer.grpc.Reference result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lightstep.tracer.grpc.Reference buildPartial() {
      com.lightstep.tracer.grpc.Reference result = new com.lightstep.tracer.grpc.Reference(this);
      result.relationship_ = relationship_;
      if (spanContextBuilder_ == null) {
        result.spanContext_ = spanContext_;
      } else {
        result.spanContext_ = spanContextBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lightstep.tracer.grpc.Reference) {
        return mergeFrom((com.lightstep.tracer.grpc.Reference)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lightstep.tracer.grpc.Reference other) {
      if (other == com.lightstep.tracer.grpc.Reference.getDefaultInstance()) return this;
      if (other.relationship_ != 0) {
        setRelationshipValue(other.getRelationshipValue());
      }
      if (other.hasSpanContext()) {
        mergeSpanContext(other.getSpanContext());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lightstep.tracer.grpc.Reference parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lightstep.tracer.grpc.Reference) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int relationship_ = 0;
    /**
     * <code>optional .lightstep.collector.Reference.Relationship relationship = 1;</code>
     */
    public int getRelationshipValue() {
      return relationship_;
    }
    /**
     * <code>optional .lightstep.collector.Reference.Relationship relationship = 1;</code>
     */
    public Builder setRelationshipValue(int value) {
      relationship_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .lightstep.collector.Reference.Relationship relationship = 1;</code>
     */
    public com.lightstep.tracer.grpc.Reference.Relationship getRelationship() {
      com.lightstep.tracer.grpc.Reference.Relationship result = com.lightstep.tracer.grpc.Reference.Relationship.valueOf(relationship_);
      return result == null ? com.lightstep.tracer.grpc.Reference.Relationship.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .lightstep.collector.Reference.Relationship relationship = 1;</code>
     */
    public Builder setRelationship(com.lightstep.tracer.grpc.Reference.Relationship value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      relationship_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .lightstep.collector.Reference.Relationship relationship = 1;</code>
     */
    public Builder clearRelationship() {
      
      relationship_ = 0;
      onChanged();
      return this;
    }

    private com.lightstep.tracer.grpc.SpanContext spanContext_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lightstep.tracer.grpc.SpanContext, com.lightstep.tracer.grpc.SpanContext.Builder, com.lightstep.tracer.grpc.SpanContextOrBuilder> spanContextBuilder_;
    /**
     * <code>optional .lightstep.collector.SpanContext span_context = 2;</code>
     */
    public boolean hasSpanContext() {
      return spanContextBuilder_ != null || spanContext_ != null;
    }
    /**
     * <code>optional .lightstep.collector.SpanContext span_context = 2;</code>
     */
    public com.lightstep.tracer.grpc.SpanContext getSpanContext() {
      if (spanContextBuilder_ == null) {
        return spanContext_ == null ? com.lightstep.tracer.grpc.SpanContext.getDefaultInstance() : spanContext_;
      } else {
        return spanContextBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .lightstep.collector.SpanContext span_context = 2;</code>
     */
    public Builder setSpanContext(com.lightstep.tracer.grpc.SpanContext value) {
      if (spanContextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        spanContext_ = value;
        onChanged();
      } else {
        spanContextBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .lightstep.collector.SpanContext span_context = 2;</code>
     */
    public Builder setSpanContext(
        com.lightstep.tracer.grpc.SpanContext.Builder builderForValue) {
      if (spanContextBuilder_ == null) {
        spanContext_ = builderForValue.build();
        onChanged();
      } else {
        spanContextBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .lightstep.collector.SpanContext span_context = 2;</code>
     */
    public Builder mergeSpanContext(com.lightstep.tracer.grpc.SpanContext value) {
      if (spanContextBuilder_ == null) {
        if (spanContext_ != null) {
          spanContext_ =
            com.lightstep.tracer.grpc.SpanContext.newBuilder(spanContext_).mergeFrom(value).buildPartial();
        } else {
          spanContext_ = value;
        }
        onChanged();
      } else {
        spanContextBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .lightstep.collector.SpanContext span_context = 2;</code>
     */
    public Builder clearSpanContext() {
      if (spanContextBuilder_ == null) {
        spanContext_ = null;
        onChanged();
      } else {
        spanContext_ = null;
        spanContextBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .lightstep.collector.SpanContext span_context = 2;</code>
     */
    public com.lightstep.tracer.grpc.SpanContext.Builder getSpanContextBuilder() {
      
      onChanged();
      return getSpanContextFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .lightstep.collector.SpanContext span_context = 2;</code>
     */
    public com.lightstep.tracer.grpc.SpanContextOrBuilder getSpanContextOrBuilder() {
      if (spanContextBuilder_ != null) {
        return spanContextBuilder_.getMessageOrBuilder();
      } else {
        return spanContext_ == null ?
            com.lightstep.tracer.grpc.SpanContext.getDefaultInstance() : spanContext_;
      }
    }
    /**
     * <code>optional .lightstep.collector.SpanContext span_context = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lightstep.tracer.grpc.SpanContext, com.lightstep.tracer.grpc.SpanContext.Builder, com.lightstep.tracer.grpc.SpanContextOrBuilder> 
        getSpanContextFieldBuilder() {
      if (spanContextBuilder_ == null) {
        spanContextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.lightstep.tracer.grpc.SpanContext, com.lightstep.tracer.grpc.SpanContext.Builder, com.lightstep.tracer.grpc.SpanContextOrBuilder>(
                getSpanContext(),
                getParentForChildren(),
                isClean());
        spanContext_ = null;
      }
      return spanContextBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:lightstep.collector.Reference)
  }

  // @@protoc_insertion_point(class_scope:lightstep.collector.Reference)
  private static final com.lightstep.tracer.grpc.Reference DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lightstep.tracer.grpc.Reference();
  }

  public static com.lightstep.tracer.grpc.Reference getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Reference>
      PARSER = new com.google.protobuf.AbstractParser<Reference>() {
    public Reference parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Reference(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Reference> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Reference> getParserForType() {
    return PARSER;
  }

  public com.lightstep.tracer.grpc.Reference getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

