// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

package com.lightstep.tracer.grpc;

public interface ReporterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightstep.collector.Reporter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 reporter_id = 1;</code>
   */
  long getReporterId();

  /**
   * <code>repeated .lightstep.collector.KeyValue tags = 4;</code>
   */
  java.util.List<com.lightstep.tracer.grpc.KeyValue> 
      getTagsList();
  /**
   * <code>repeated .lightstep.collector.KeyValue tags = 4;</code>
   */
  com.lightstep.tracer.grpc.KeyValue getTags(int index);
  /**
   * <code>repeated .lightstep.collector.KeyValue tags = 4;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated .lightstep.collector.KeyValue tags = 4;</code>
   */
  java.util.List<? extends com.lightstep.tracer.grpc.KeyValueOrBuilder> 
      getTagsOrBuilderList();
  /**
   * <code>repeated .lightstep.collector.KeyValue tags = 4;</code>
   */
  com.lightstep.tracer.grpc.KeyValueOrBuilder getTagsOrBuilder(
      int index);
}
