// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

package com.lightstep.tracer.grpc;

public interface SpanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightstep.collector.Span)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .lightstep.collector.SpanContext span_context = 1;</code>
   */
  boolean hasSpanContext();
  /**
   * <code>optional .lightstep.collector.SpanContext span_context = 1;</code>
   */
  com.lightstep.tracer.grpc.SpanContext getSpanContext();
  /**
   * <code>optional .lightstep.collector.SpanContext span_context = 1;</code>
   */
  com.lightstep.tracer.grpc.SpanContextOrBuilder getSpanContextOrBuilder();

  /**
   * <code>optional string operation_name = 2;</code>
   */
  java.lang.String getOperationName();
  /**
   * <code>optional string operation_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getOperationNameBytes();

  /**
   * <code>repeated .lightstep.collector.Reference references = 3;</code>
   */
  java.util.List<com.lightstep.tracer.grpc.Reference> 
      getReferencesList();
  /**
   * <code>repeated .lightstep.collector.Reference references = 3;</code>
   */
  com.lightstep.tracer.grpc.Reference getReferences(int index);
  /**
   * <code>repeated .lightstep.collector.Reference references = 3;</code>
   */
  int getReferencesCount();
  /**
   * <code>repeated .lightstep.collector.Reference references = 3;</code>
   */
  java.util.List<? extends com.lightstep.tracer.grpc.ReferenceOrBuilder> 
      getReferencesOrBuilderList();
  /**
   * <code>repeated .lightstep.collector.Reference references = 3;</code>
   */
  com.lightstep.tracer.grpc.ReferenceOrBuilder getReferencesOrBuilder(
      int index);

  /**
   * <code>optional .google.protobuf.Timestamp start_timestamp = 4;</code>
   */
  boolean hasStartTimestamp();
  /**
   * <code>optional .google.protobuf.Timestamp start_timestamp = 4;</code>
   */
  com.google.protobuf.Timestamp getStartTimestamp();
  /**
   * <code>optional .google.protobuf.Timestamp start_timestamp = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartTimestampOrBuilder();

  /**
   * <code>optional uint64 duration_micros = 5;</code>
   */
  long getDurationMicros();

  /**
   * <code>repeated .lightstep.collector.KeyValue tags = 6;</code>
   */
  java.util.List<com.lightstep.tracer.grpc.KeyValue> 
      getTagsList();
  /**
   * <code>repeated .lightstep.collector.KeyValue tags = 6;</code>
   */
  com.lightstep.tracer.grpc.KeyValue getTags(int index);
  /**
   * <code>repeated .lightstep.collector.KeyValue tags = 6;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated .lightstep.collector.KeyValue tags = 6;</code>
   */
  java.util.List<? extends com.lightstep.tracer.grpc.KeyValueOrBuilder> 
      getTagsOrBuilderList();
  /**
   * <code>repeated .lightstep.collector.KeyValue tags = 6;</code>
   */
  com.lightstep.tracer.grpc.KeyValueOrBuilder getTagsOrBuilder(
      int index);

  /**
   * <code>repeated .lightstep.collector.Log logs = 7;</code>
   */
  java.util.List<com.lightstep.tracer.grpc.Log> 
      getLogsList();
  /**
   * <code>repeated .lightstep.collector.Log logs = 7;</code>
   */
  com.lightstep.tracer.grpc.Log getLogs(int index);
  /**
   * <code>repeated .lightstep.collector.Log logs = 7;</code>
   */
  int getLogsCount();
  /**
   * <code>repeated .lightstep.collector.Log logs = 7;</code>
   */
  java.util.List<? extends com.lightstep.tracer.grpc.LogOrBuilder> 
      getLogsOrBuilderList();
  /**
   * <code>repeated .lightstep.collector.Log logs = 7;</code>
   */
  com.lightstep.tracer.grpc.LogOrBuilder getLogsOrBuilder(
      int index);
}
