// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

package com.lightstep.tracer.grpc;

public interface SpanContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightstep.collector.SpanContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 trace_id = 1;</code>
   */
  long getTraceId();

  /**
   * <code>optional uint64 span_id = 2;</code>
   */
  long getSpanId();

  /**
   * <code>map&lt;string, string&gt; baggage = 3;</code>
   */
  int getBaggageCount();
  /**
   * <code>map&lt;string, string&gt; baggage = 3;</code>
   */
  boolean containsBaggage(
          String key);
  /**
   * Use {@link #getBaggageMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getBaggage();
  /**
   * <code>map&lt;string, string&gt; baggage = 3;</code>
   */
  java.util.Map<String, String>
  getBaggageMap();
  /**
   * <code>map&lt;string, string&gt; baggage = 3;</code>
   */

  String getBaggageOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; baggage = 3;</code>
   */

  String getBaggageOrThrow(
          String key);
}
